/*
 * This source file was generated by the Gradle 'init' task
 */
package umaengine;

import umaengine.obj.Race;

public class App {
    private Race raceobj;

    public String getName() {
        return "Program";
    }

    public static void main(String[] args) {
        App a = new App();
        System.out.println("My name is: " + a.getName() + "!");
        a.raceobj = new Race(12);
        a.raceobj.setName(args[0]);
        System.out.println("Race has name: " + a.raceobj.returnName() + ".");
    }
}
